#!/bin/bash
echo -e "\e[32m
Expense manager

\e[39m"
case "$1" in
	docker)
        arg=${3-app}
        case "$2" in
            up)
                (docker-compose up)
            ;;
            down)
                (cd docker && docker-compose down)
            ;;
			build)
				(docker-compose build)
			;;
            ssh)
                (docker exec -it ${arg} /bin/bash )
            ;;
            migrate)
                (docker exec -it ${arg} php artisan migrate)
            ;;
            rollback)
                (docker exec -it ${arg} php artisan migrate:rollback)
            ;;
        esac
        ;;
    artisan)
        migration=( $(php $@) )
				migrationname=${migration[2]}
				echo $migration
				if [ "$2" == 'make:migration' ]
				then
					year=$(echo "$migrationname" |cut -d '_' -f 1)
					month=$(echo "$migrationname" |cut -d '_' -f 2)
					atom ./database/migrations/${year}/${month}/${migration[2]}.php
				fi
    ;;
    migrate)
        ./manager docker migrate
    ;;
    migrate-step)
        ./manager docker migrate --step
    ;;
    rollback)
        ./manager docker rollback
    ;;
    rollback-step)
    ./manager docker rollback --step
    ;;
    ab)
        read -p 'PHPSESSID : ' phpsessid
        read -e -p "Nombre de requêtes : " -i "500" nb
        read -p 'URL à tester : ' url
        (cd docker && docker exec -it docker_apache_1 ab -C PHPSESSID=${phpsessid} -n ${nb} -c 2 http://localhost/${url})
    ;;
esac
